version: '3'
services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - .:/usr/app
      - ./controllers:/usr/app/controllers
      - ./helpers:/usr/app/helpers
      - ./routers:/usr/app/routers
      - ./services:/usr/app/services
      - ./models:/usr/app/models
      - ./config:/usr/app/config
      - /usr/app/node_modules
  db:
    container_name: db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
volumes:
  mongo:
