version: "3"
services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
